# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NloglikFD1 <- function(par, outdata_F, outdata_proband, Age, Cal, lam03, full, fgau, fdpexp, fppexp, combn) {
    .Call(`_clusteridm_NloglikFD1`, par, outdata_F, outdata_proband, Age, Cal, lam03, full, fgau, fdpexp, fppexp, combn)
}

NloglikFD2 <- function(par, outdata_F, outdata_proband, Age, Cal, lam03, fgau, fdpexp, fppexp, combn, ppch) {
    .Call(`_clusteridm_NloglikFD2`, par, outdata_F, outdata_proband, Age, Cal, lam03, fgau, fdpexp, fppexp, combn, ppch)
}

loglikFD1 <- function(par, outdata_F, outdata_proband, Age, Cal, lam03, full, fgau, fdpexp, fppexp, combn) {
    .Call(`_clusteridm_loglikFD1`, par, outdata_F, outdata_proband, Age, Cal, lam03, full, fgau, fdpexp, fppexp, combn)
}

loglikFD2 <- function(par, outdata_F, outdata_proband, Age, Cal, lam03, fgau, fdpexp, fppexp, combn, ppch) {
    .Call(`_clusteridm_loglikFD2`, par, outdata_F, outdata_proband, Age, Cal, lam03, fgau, fdpexp, fppexp, combn, ppch)
}

loglikR <- function(outdata_R, par, LAM03R, cutR, fgau, fdpexp, fppexp) {
    .Call(`_clusteridm_loglikR`, outdata_R, par, LAM03R, cutR, fgau, fdpexp, fppexp)
}

loglikS <- function(outdata_S, par, LAM03S, cutS, fgau, fdpexp, fppexp) {
    .Call(`_clusteridm_loglikS`, outdata_S, par, LAM03S, cutS, fgau, fdpexp, fppexp)
}

NloglikS <- function(outdata_S, par, LAM03S, cutS, fgau, fdpexp, fppexp) {
    .Call(`_clusteridm_NloglikS`, outdata_S, par, LAM03S, cutS, fgau, fdpexp, fppexp)
}

